//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilioConsole.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here&apos;s whassup.
        /// </summary>
        internal static string AccountChannel_BadTokens {
            get {
                return ResourceManager.GetString("AccountChannel_BadTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123123.
        /// </summary>
        internal static string AccountChannel_ChannelMissing {
            get {
                return ResourceManager.GetString("AccountChannel_ChannelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s for {0}?.
        /// </summary>
        internal static string MealQuestion {
            get {
                return ResourceManager.GetString("MealQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new content from {0} to read..
        /// </summary>
        internal static string NewContent {
            get {
                return ResourceManager.GetString("NewContent", resourceCulture);
            }
        }
    }
}
